"""Auto-generovaný seznam kategorií z manuálně stažených HTML"""

# Zpracováno 20/20 sekcí
# Celkem 1642 kategorií

CATEGORIES = {
    "Biuro": [
        "Akcesoria do komputerów",
        "Artykuły biurowe",
        "Artykuły i sprzęt BHP",
        "Artykuły papiernicze",
        "Artykuły szkolne",
        "Audyty oprogramowania i sprzętu komputerowego",
        "Części komputerowe",
        "Drukarki i urządzenia peryferyjne",
        "Etykiety i naklejki",
        "Folie i foliowanie",
        "Hurtownie artykułów biurowych",
        "Hurtownie artykułów papierniczych",
        "Hurtownie dywanów i wykładzin",
        "Ksero",
        "Meble biurowe",
        "Meble metalowe",
        "Oprogramowanie komputerowe",
        "Papier",
        "Pieczątki i stemple",
        "Pomiary, konsultacje i badania BHP",
        "Producenci artykułów biurowych",
        "Produkcja artykułów papierniczych",
        "Serwis komputerów",
        "Serwis kserokopiarek",
        "Sieci komputerowe i integracja systemów",
        "Sprzedaż komputerów",
        "Sprzęt i centrale telefoniczne",
        "Systemy audiowizualne",
        "Systemy i technologie multimedialne",
        "Taśmy samoprzylepne",
        "Wynajem i sprzedaż kserokopiarek",
        "Wyposażenie biur",
        "Zaopatrzenie biur",
    ],
    "Budownictwo": [
        "Adwokaci",
        "Agencje ochrony",
        "Agregaty prądotwórcze",
        "Agregaty, komory i meble chłodnicze",
        "Akcesoria do drzwi i okien",
        "Akcesoria meblowe",
        "Alarmy samochodowe",
        "Amortyzatory samochodowe",
        "Architektura krajobrazu",
        "Armatura hydrauliczna",
        "Armatura przemysłowa",
        "Artykuły elektrotechniczne",
        "Artykuły gumowe",
        "Artykuły i sprzęt ogrodniczy",
        "Artykuły metalowe",
        "Automatyka",
        "Badania i usługi archeologiczne",
        "Badania i uzdatnianie wody",
        "Badania nieniszczące",
        "Beton",
        "Biura architektoniczne",
        "Biura projektowe",
        "Blacharstwo i lakiernictwo",
        "Bramy i ogrodzenia",
        "Brukarstwo",
        "Budowa i eksploatacja autostrad",
        "Budowa i eksploatacja rurociągów",
        "Budowa i sprzęt drogowy",
        "Budowa i wykończenia pod klucz",
        "Budowa i wynajem hal przemysłowych",
        "Budowa i wyposażenie garaży",
        "Budowa i wyposażenie saun",
        "Budowa i wyposażenie stacji paliw",
        "Budowa obiektów sportowych",
        "Budowa, wyposażenie i remont statków",
        "Budownictwo kolejowe",
        "Budownictwo przemysłowe",
        "Car audio",
        "Cegły",
        "Cement i wapno",
        "Ceramika budowlana",
        "Chemia budowlana",
        "Chemia gospodarcza",
        "Cięcie i wiercenie",
        "Cięcie i wiercenie w betonie",
        "Cięcie i zaginanie",
        "Czyszczenie i renowacja dywanów i wykładzin",
        "Czyszczenie strumieniowo-ścierne",
        "Czyszczące urządzenia przemysłowe",
        "Dachy i rynny",
        "Dachy i usługi dekarskie",
        "Dealerzy i sprzedaż samochodów",
        "Dekoratorstwo i architektura wnętrz",
        "Deweloperzy",
        "Doradztwo finansowe i kredytowe",
        "Drabiny",
        "Drewno",
        "Drewno budowlane",
        "Drewno opałowe",
        "Drut i liny stalowe",
        "Drzwi",
        "Drzwi antywłamaniowe",
        "Dystrybucja energii elektrycznej",
        "Dywany i wykładziny",
        "Dźwigi i żurawie",
        "Dźwignice",
        "Ekspertyzy i kosztorysy budowlane",
        "Elektroinstalatorstwo",
        "Elektromechanika",
        "Elektronarzędzia",
        "Elektronika samochodowa",
        "Farby i lakiery",
        "Filtry",
        "Firmy konsultingowe",
        "Folie i foliowanie",
        "Formy wtryskowe",
        "Galwanizacja",
        "Gaz ziemny",
        "Gazy techniczne",
        "Geodezja",
        "Geolodzy i geofizycy",
        "Geosyntetyki",
        "Gres, terakota i płytki ceramiczne",
        "Haki holownicze",
        "Hurtownie artykułów elektrotechnicznych",
        "Hurtownie artykułów metalowych",
        "Hurtownie chemii gospodarczej",
        "Hurtownie części samochodowych",
        "Hurtownie dywanów i wykładzin",
        "Hurtownie farb, lakierów i emalii",
        "Hurtownie gresu, terakoty i płytek ceramicznych",
        "Hurtownie parkietu i paneli podłogowych",
        "Hurtownie urządzeń elektrycznych",
        "Hurtownie urządzeń sanitarnych",
        "Hurtownie żaluzji i rolet",
        "Hydraulicy",
        "Hydraulika siłowa",
        "Hydrotechnika",
        "Instalacja i serwis ogrzewania",
        "Instalacja systemów alarmowych",
        "Instalacje energetyczne i ciepłownicze",
        "Instalacje i urządzenia energetyczne",
        "Instalacje przemysłowe",
        "Instalacje systemów teletechnicznych",
        "Instalacje termoizolacyjne",
        "Inwestycje budowlane",
        "Izolacja akustyczna",
        "Izolacja termiczna",
        "Izolacja wodochronna",
        "Kamień i kruszywa",
        "Kleje i żywice",
        "Klimatyzacja",
        "Klimatyzacja samochodowa",
        "Kominiarze",
        "Kominki",
        "Kominy",
        "Kompresory",
        "Konserwacja zabytków",
        "Konstrukcje aluminiowe",
        "Konstrukcje stalowe",
        "Kontenery",
        "Korek naturalny",
        "Kosmetyki samochodowe",
        "Kostka brukowa",
        "Koła i zestawy jezdne",
        "Kraty pomostowe",
        "Kredyty i finansowanie",
        "Lakiery samochodowe",
        "Laminaty",
        "Liczniki energii elektrycznej",
        "Lustra",
        "Magnesy i elektromagnesy",
        "Malowanie i lakierowanie proszkowe",
        "Malowanie i lakierowanie przemysłowe",
        "Malowanie i tapetowanie",
        "Mapy i plany",
        "Marmur, granit i kamień naturalny",
        "Maszty i słupy",
        "Maszyny do obróbki drewna",
        "Maszyny do obróbki metali",
        "Maszyny pakujące",
        "Materiały budowlane",
        "Materiały do spawania i zgrzewania",
        "Materiały do wykańczania wnętrz",
        "Materiały drewnopochodne",
        "Materiały elektryczne",
        "Materiały elewacyjne",
        "Materiały izolacyjne",
        "Materiały ognioodporne",
        "Materiały opałowe",
        "Materiały tapicerskie",
        "Materiały ścierne i polerskie",
        "Meble",
        "Meble biurowe",
        "Meble kuchenne",
        "Meble metalowe",
        "Meble na zamówienie",
        "Meble ogrodowe",
        "Mechanika samochodowa",
        "Metale nieżelazne i kolorowe",
        "Metale żelazne",
        "Metalizowanie i powlekanie tworzyw",
        "Metaloplastyka",
        "Montaż i produkcja basenów i fontann",
        "Montaż i sprzedaż żaluzji i rolet",
        "Naczepy samochodowe",
        "Nadzór budowlany",
        "Napełnianie butli gazowych",
        "Narzędzia",
        "Nieruchomości",
        "Obróbka metali",
        "Obróbka tworzyw sztucznych",
        "Oczyszczanie ścieków",
        "Odkurzacze centralne",
        "Odlewnie",
        "Odzież robocza",
        "Ogrodnictwo",
        "Ogrzewanie elektryczne",
        "Okleiny",
        "Oklejanie samochodów",
        "Okna",
        "Okna dachowe",
        "Okna drewniane",
        "Okucia",
        "Olej opałowy",
        "Oleje techniczne i smary",
        "Opakowania",
        "Opakowania foliowe",
        "Opakowania papierowe i tekturowe",
        "Opakowania z tworzyw sztucznych",
        "Osuszanie budynków",
        "Oznakowanie i sygnalizacja dróg",
        "Oświetlenie",
        "Palety",
        "Paliwa",
        "Panele i podłogi",
        "Parapety",
        "Parkiet i panele podłogowe",
        "Pasy napędowe i transportujące",
        "Piece",
        "Plandeki",
        "Pneumatyka siłowa",
        "Podnośniki",
        "Pojazdy specjalistyczne",
        "Pompy",
        "Poręcze i balustrady",
        "Posadzki przemysłowe",
        "Pośrednicy ubezpieczeniowi",
        "Prace elewacyjne",
        "Prace podwodne",
        "Prace wysokościowe",
        "Prefabrykaty budowlane",
        "Producenci domów drewnianych",
        "Producenci farb i lakierów",
        "Produkcja artykułów elektrotechnicznych",
        "Produkcja artykułów metalowych",
        "Produkcja części samochodowych",
        "Produkcja i hurtownie narzędzi",
        "Produkcja i montaż domofonów",
        "Produkcja i montaż szamb",
        "Produkcja i sprzedaż opon",
        "Produkcja kryształów i szkła ozdobnego",
        "Produkcja maszyn budowlanych",
        "Produkcja parkietu i paneli podłogowych",
        "Produkcja sprężyn",
        "Produkcja systemów alarmowych",
        "Produkcja urządzeń elektronicznych",
        "Produkcja urządzeń elektrycznych",
        "Produkcja urządzeń sanitarnych",
        "Produkcja zasłon, firanek i karniszy",
        "Produkcja żaluzji i rolet",
        "Projektowanie i montaż placów zabaw",
        "Przekładnie",
        "Przemysłowe urządzenia elektryczne",
        "Przenośniki",
        "Przeprowadzki",
        "Przewody, kable i światłowody",
        "Przyczepy samochodowe",
        "Pędzle i szczotki",
        "Radcy prawni",
        "Regeneracja części samochodowych",
        "Renowacja mebli",
        "Renowacje i remonty",
        "Rury",
        "Rusztowania i szalunki",
        "Rzeczoznawcy",
        "Samochodowe agregaty chłodnicze",
        "Samochodowe instalacje gazowe",
        "Samochody używane",
        "Schody",
        "Serwis i części do maszyn budowlanych",
        "Serwis i instalacja klimatyzacji",
        "Serwis samochodów ciężarowych i dostawczych",
        "Serwis urządzeń chłodniczych",
        "Serwis urządzeń elektrycznych",
        "Silikon",
        "Silniki i prądnice",
        "Siłowniki i automatyczne napędy do bram",
        "Skrzynie biegów",
        "Spedycja",
        "Spedycja międzynarodowa",
        "Sprzedaż maszyn budowlanych",
        "Sprzedaż samochodów ciężarowych i dostawczych",
        "Sprzątanie terenu",
        "Sprzątanie wnętrz i mycie okien",
        "Sprzęt do malowania i tapetowania",
        "Sprzęt do produkcji opakowań",
        "Sprzęt i materiały hydrauliczne",
        "Sprzęt i zabezpieczenia przeciwpożarowe",
        "Sprzęt torowy i kolejowy",
        "Spółdzielnie i administracje mieszkaniowe",
        "Stacje diagnostyczne i przeglądy techniczne",
        "Stacje obsługi i warsztaty samochodowe",
        "Stal i wyroby stalowe",
        "Stolarze",
        "Studnie",
        "Styropian",
        "Sufity podwieszane",
        "Surowce mineralne",
        "Suwnice",
        "Systemy dźwiękowe i audio",
        "Systemy zabudowy wnętrz",
        "Systemy zamocowań",
        "Szklarze",
        "Szkło budowlane",
        "Szkło przemysłowe",
        "Sznury, liny i nici",
        "Szyberdachy",
        "Szyby samochodowe",
        "Tablice rejestracyjne",
        "Tabor kolejowy",
        "Taksometry, tachometry i tachografy",
        "Tapety",
        "Tapicerka i pokrowce samochodowe",
        "Tartaki",
        "Techniki bezwykopowe",
        "Technologie budowlane",
        "Telewizja przemysłowa",
        "Transport kolejowy",
        "Transport lotniczy",
        "Transport międzynarodowy",
        "Transport morski i śródlądowy",
        "Transport nadgabarytowy",
        "Transport samochodowy",
        "Transport ładunków niebezpiecznych",
        "Tworzywa sztuczne",
        "Tłumiki i układy wydechowe",
        "Ubezpieczenia",
        "Układanie gresu i płytek ceramicznych",
        "Układanie wykładzin podłogowych",
        "Urządzenia elektroniczne",
        "Urządzenia elektryczne",
        "Urządzenia gazowe",
        "Urządzenia grzewcze",
        "Urządzenia i maszyny przemysłowe",
        "Urządzenia lakiernicze",
        "Urządzenia pneumatyczne",
        "Urządzenia pomiarowe",
        "Urządzenia sanitarne",
        "Urządzenia spawalnicze i zgrzewające",
        "Usuwanie i neutralizacja azbestu",
        "Uszczelki i uszczelnienia",
        "Usługi gazownicze",
        "Usługi i projekty górnicze",
        "Usługi kamieniarskie",
        "Usługi posadzkarskie",
        "Usługi saperskie",
        "Usługi spawania i zgrzewania",
        "Usługi tapicerskie",
        "Usługi wodno-kanalizacyjne",
        "Utylizacja odpadów",
        "Uzbrajanie terenu",
        "Używane części samochodowe",
        "Wagi",
        "Wentylacja",
        "Windy i urządzenia dźwigowe",
        "Witraże",
        "Wodociągi i kanalizacja",
        "Wulkanizacja i serwis opon",
        "Wyburzenia i rozbiórki",
        "Wycena nieruchomości",
        "Wycieraczki i maty",
        "Wykopy i roboty fundamentowe",
        "Wykończenia wnętrz",
        "Wynajem dźwigów i żurawi",
        "Wynajem magazynów",
        "Wynajem maszyn budowlanych",
        "Wynajem maszyn i narzędzi",
        "Wynajem samochodów ciężarowych i dostawczych",
        "Wynajem samochodów i zarządzanie flotą",
        "Wyposażenie dodatkowe samochodów",
        "Wyposażenie hoteli",
        "Wyposażenie kuchni",
        "Wyposażenie magazynów",
        "Wyposażenie obiektów sportowych",
        "Wyposażenie sklepów",
        "Wyposażenie warsztatów i myjni samochodowych",
        "Wyposażenie łazienek",
        "Wyroby hutnicze",
        "Wytwarzanie energii odnawialnej",
        "Wywóz śmieci i odpadów",
        "Wzornictwo przemysłowe",
        "Wózki widłowe",
        "Węże przemysłowe",
        "Zabezpieczenia antykorozyjne",
        "Zabezpieczenia antykorozyjne samochodów",
        "Zabudowy nadwozi samochodowych",
        "Zakłady sztukatorskie",
        "Zamki i kłódki",
        "Zamki i zabezpieczenia antywłamaniowe",
        "Zarządzanie nieruchomościami",
        "Zawiesia linowe, łańcuchowe i pasowe",
        "Zbiorniki i pojemniki",
        "Znakowanie i monitorowanie samochodów",
        "Złom i surowce wtórne",
        "Łańcuchy",
        "Łożyska",
        "Ślusarze",
        "Świadectwa energetyczne",
    ],
    "Dom i ogród": [
        "Akcesoria do drzwi i okien",
        "Akcesoria meblowe",
        "Anteny",
        "Architektura krajobrazu",
        "Armatura hydrauliczna",
        "Artykuły i sprzęt ogrodniczy",
        "Biura architektoniczne",
        "Biura projektowe",
        "Bramy i ogrodzenia",
        "Brykiety i węgiel drzewny",
        "Budowa i wykończenia pod klucz",
        "Budowa i wyposażenie garaży",
        "Ceramika ozdobna",
        "Chemia gospodarcza",
        "Czyszczenie i renowacja dywanów i wykładzin",
        "Dachy i rynny",
        "Dekoratorstwo i architektura wnętrz",
        "Deweloperzy",
        "Dozowniki mydła",
        "Drewno opałowe",
        "Drzwi",
        "Drzwi antywłamaniowe",
        "Dywany i wykładziny",
        "Elektroinstalatorstwo",
        "Filtry",
        "Folie i foliowanie",
        "Gres, terakota i płytki ceramiczne",
        "Grzejnictwo elektryczne",
        "Hurtownie RTV",
        "Hurtownie artykułów higienicznych",
        "Hurtownie dywanów i wykładzin",
        "Hurtownie gresu, terakoty i płytek ceramicznych",
        "Hurtownie parkietu i paneli podłogowych",
        "Hurtownie sprzętu AGD",
        "Hurtownie szkła ozdobnego i kryształów",
        "Hurtownie urządzeń elektrycznych",
        "Hurtownie urządzeń sanitarnych",
        "Hurtownie zasłon, firanek i karniszy",
        "Hurtownie żaluzji i rolet",
        "Hydraulicy",
        "Hydraulika siłowa",
        "Instalacja i serwis ogrzewania",
        "Instalacja systemów alarmowych",
        "Kominiarze",
        "Kominki",
        "Kominy",
        "Kryształy i szkło ozdobne",
        "Lampy i oświetlenie wnętrz",
        "Lustra",
        "Magiel",
        "Malowanie i tapetowanie",
        "Maszyny dziewiarskie",
        "Materace",
        "Materiały do wykańczania wnętrz",
        "Materiały drewnopochodne",
        "Materiały elektryczne",
        "Materiały tapicerskie",
        "Meble",
        "Meble biurowe",
        "Meble kuchenne",
        "Meble metalowe",
        "Meble na zamówienie",
        "Meble ogrodowe",
        "Meble specjalistyczne",
        "Montaż i produkcja basenów i fontann",
        "Montaż i sprzedaż żaluzji i rolet",
        "Napełnianie butli gazowych",
        "Nośniki danych i płyty CD i DVD",
        "Obrusy",
        "Oczyszczanie ścieków",
        "Odkurzacze centralne",
        "Ogrodnictwo",
        "Ogrzewanie elektryczne",
        "Okleiny",
        "Okna",
        "Okna dachowe",
        "Okna drewniane",
        "Ozdoby świąteczne",
        "Oświetlenie",
        "Panele i podłogi",
        "Parapety",
        "Parkiet i panele podłogowe",
        "Pomoc domowa",
        "Porcelana i fajans",
        "Poręcze i balustrady",
        "Posadzki przemysłowe",
        "Producenci domów drewnianych",
        "Produkcja artykułów higienicznych",
        "Produkcja i hurtownie narzędzi",
        "Produkcja i montaż domofonów",
        "Produkcja kryształów i szkła ozdobnego",
        "Produkcja parkietu i paneli podłogowych",
        "Produkcja roślin i nasion",
        "Produkcja sprzętu AGD",
        "Produkcja sprzętu RTV",
        "Produkcja systemów alarmowych",
        "Produkcja urządzeń elektronicznych",
        "Produkcja urządzeń elektrycznych",
        "Produkcja urządzeń sanitarnych",
        "Produkcja zasłon, firanek i karniszy",
        "Produkcja żaluzji i rolet",
        "Ramy i oprawy obrazów",
        "Renowacja mebli",
        "Renowacje i remonty",
        "Rośliny sztuczne",
        "Rośliny, nasiona i cebulki",
        "Ręczniki, koce i pościel",
        "Schody",
        "Serwis RTV",
        "Serwis sprzętu AGD",
        "Serwis urządzeń elektrycznych",
        "Sklepy ze sprzętem AGD",
        "Sklepy ze sprzętem RTV",
        "Sprzątanie wnętrz i mycie okien",
        "Sprzęt do malowania i tapetowania",
        "Sprzęt i materiały hydrauliczne",
        "Sprzęt i zabezpieczenia przeciwpożarowe",
        "Stolarze",
        "Studnie",
        "Sufity podwieszane",
        "Systemy audiowizualne",
        "Systemy dźwiękowe i audio",
        "Systemy zabudowy wnętrz",
        "Szklarze",
        "Tapety",
        "Telewizja kablowa",
        "Telewizja satelitarna",
        "Układanie gresu i płytek ceramicznych",
        "Układanie wykładzin podłogowych",
        "Urządzenia elektroniczne",
        "Urządzenia elektryczne",
        "Urządzenia grzewcze",
        "Urządzenia sanitarne",
        "Uszczelki i uszczelnienia",
        "Usługi gazownicze",
        "Usługi kamieniarskie",
        "Usługi posadzkarskie",
        "Usługi tapicerskie",
        "Witraże",
        "Wodociągi i kanalizacja",
        "Wycieraczki i maty",
        "Wykończenia wnętrz",
        "Wyposażenie kuchni",
        "Wyposażenie łazienek",
        "Wyroby wiklinowe i bambusowe",
        "Wywóz śmieci i odpadów",
        "Zamki i kłódki",
        "Zamki i zabezpieczenia antywłamaniowe",
        "Zapalniczki i zapałki",
        "Zasłony, firanki i karnisze",
        "Zawiesia linowe, łańcuchowe i pasowe",
        "Ślusarstwo i dorabianie kluczy",
        "Ślusarze",
        "Środki ochrony roślin",
        "Świece i znicze",
    ],
    "Dzieci": [
        "Artykuły dziecięce",
        "Artykuły papiernicze",
        "Artykuły szkolne",
        "Domy dziecka",
        "Hurtownie artykułów papierniczych",
        "Hurtownie i producenci artykułów dziecięcych",
        "Hurtownie zabawek",
        "Logopedzi",
        "Odzież dziecięca",
        "Opieka nad dziećmi",
        "Ośrodki adopcyjno-wychowawcze",
        "Ośrodki szkolno-wychowawcze",
        "Ośrodki wychowawcze",
        "Parki rozrywki",
        "Produkcja artykułów papierniczych",
        "Produkcja zabawek",
        "Projektowanie i montaż placów zabaw",
        "Przedszkola prywatne",
        "Przedszkola publiczne",
        "Sale zabaw",
        "Sklepy z zabawkami",
        "Zabawki edukacyjne",
        "Świetlice środowiskowe",
        "Żłobki prywatne",
        "Żłobki publiczne",
    ],
    "Finanse i ubezpieczenia": [
        "Banki",
        "Bankomaty",
        "Biura rachunkowe",
        "Doradztwo finansowe i kredytowe",
        "Doradztwo podatkowe",
        "Fundusze emerytalne",
        "Fundusze inwestycyjne",
        "Giełdy",
        "Kantory",
        "Karty kredytowe, płatnicze i programy lojalnościowe",
        "Kredyty i finansowanie",
        "Leasing",
        "Maklerzy giełdowi",
        "Oddłużanie",
        "Pośrednicy ubezpieczeniowi",
        "Sprzęt i wyposażenie banków",
        "Ubezpieczenia",
        "Ubezpieczenia społeczne",
        "Windykacja długów i należności",
    ],
    "Instytucje, urzędy": [
        "Administracja obiektów użyteczności publicznej",
        "Agencje i składy celne",
        "Ambasady",
        "Archiwa i archiwizacja danych",
        "Biblioteki i czytelnie",
        "Dobry Start - 300 zł dla ucznia",
        "Fundacje i instytucje charytatywne",
        "Inkubatory przedsiębiorczości",
        "Internaty i akademiki",
        "Konserwacja zabytków",
        "Militaria",
        "Narodowy Fundusz Zdrowia",
        "Ochrona środowiska",
        "Ośrodki adopcyjno-wychowawcze",
        "Ośrodki wychowawcze",
        "Poczta i urzędy pocztowe",
        "Pogotowie ratunkowe",
        "Policja",
        "Prokuratury",
        "Rodzina 500 Plus",
        "Rzecznicy patentowi",
        "Sołectwa",
        "Specjalne strefy ekonomiczne",
        "Spółdzielnie i administracje mieszkaniowe",
        "Stacje sanitarno-epidemiologiczne",
        "Starostwa powiatowe",
        "Stowarzyszenia, kluby i związki",
        "Straż miejska",
        "Straż pożarna",
        "Syndycy i likwidatorzy",
        "Sądy",
        "Telefony alarmowe",
        "Telefony zaufania",
        "Unia Europejska",
        "Urzędy celne",
        "Urzędy centralne",
        "Urzędy marszałkowskie",
        "Urzędy miast i gmin",
        "Urzędy pracy",
        "Urzędy skarbowe",
        "Urzędy terenowe",
        "Urzędy wojewódzkie",
        "Więzienia i zakłady penitencjarne",
        "Zarządy cmentarzy i cmentarze",
    ],
    "Kancelaria": [
        "Akcesoria do komputerów",
        "Artykuły biurowe",
        "Artykuły i sprzęt BHP",
        "Artykuły papiernicze",
        "Artykuły szkolne",
        "Audyty oprogramowania i sprzętu komputerowego",
        "Części komputerowe",
        "Drukarki i urządzenia peryferyjne",
        "Etykiety i naklejki",
        "Folie i foliowanie",
        "Hurtownie artykułów biurowych",
        "Hurtownie artykułów papierniczych",
        "Hurtownie dywanów i wykładzin",
        "Ksero",
        "Meble biurowe",
        "Meble metalowe",
        "Oprogramowanie komputerowe",
        "Papier",
        "Pieczątki i stemple",
        "Pomiary, konsultacje i badania BHP",
        "Producenci artykułów biurowych",
        "Produkcja artykułów papierniczych",
        "Serwis komputerów",
        "Serwis kserokopiarek",
        "Sieci komputerowe i integracja systemów",
        "Sprzedaż komputerów",
        "Sprzęt i centrale telefoniczne",
        "Systemy audiowizualne",
        "Systemy i technologie multimedialne",
        "Taśmy samoprzylepne",
        "Wynajem i sprzedaż kserokopiarek",
        "Wyposażenie biur",
        "Zaopatrzenie biur",
    ],
    "Motoryzacja i transport": [
        "Agenci okrętowi i morscy",
        "Alarmy samochodowe",
        "Amortyzatory samochodowe",
        "Artykuły pogrzebowe",
        "Autozłom",
        "Blacharstwo i lakiernictwo",
        "Budowa i wyposażenie garaży",
        "Car audio",
        "Dealerzy i sprzedaż samochodów",
        "Elektromechanika",
        "Elektronika samochodowa",
        "Folie i foliowanie",
        "Giełdy",
        "Haki holownicze",
        "Hurtownie części samochodowych",
        "Instalacja systemów alarmowych",
        "Kampery i przyczepy kempingowe",
        "Klimatyzacja samochodowa",
        "Komunikacja i przewozy pasażerskie",
        "Kosmetyki samochodowe",
        "Koła i zestawy jezdne",
        "Lakiery samochodowe",
        "Linie lotnicze",
        "Lotniska",
        "Mechanika samochodowa",
        "Mobilne myjnie samochodowe",
        "Motocykle, skutery i quady",
        "Myjnie samochodowe",
        "Naczepy samochodowe",
        "Nawigacja i lokalizacja satelitarna",
        "Oklejanie samochodów",
        "Operatorzy logistyczni",
        "Paliwa",
        "Parkingi",
        "Plandeki",
        "Pojazdy specjalistyczne",
        "Pojazdy zabytkowe i dorożki",
        "Pomoc drogowa",
        "Produkcja części samochodowych",
        "Produkcja i sprzedaż opon",
        "Przekładnie",
        "Przeprowadzki",
        "Przewozy autokarowe",
        "Przewozy osób niepełnosprawnych",
        "Przyczepy samochodowe",
        "Punkty ładowania samochodów elektrycznych",
        "Regeneracja części samochodowych",
        "Rejestracja pojazdów",
        "Samochodowe agregaty chłodnicze",
        "Samochodowe instalacje gazowe",
        "Samochody używane",
        "Serwis samochodów ciężarowych i dostawczych",
        "Silniki i prądnice",
        "Skrzynie biegów",
        "Spedycja",
        "Spedycja międzynarodowa",
        "Sprzedaż części samochodowych",
        "Sprzedaż i rezerwacja biletów",
        "Sprzedaż samochodów ciężarowych i dostawczych",
        "Sprzęt lotniczy",
        "Sprzęt torowy i kolejowy",
        "Stacje diagnostyczne i przeglądy techniczne",
        "Stacje obsługi i warsztaty samochodowe",
        "Stacje paliw",
        "Szyberdachy",
        "Szyby samochodowe",
        "Tablice rejestracyjne",
        "Tabor kolejowy",
        "Taksometry, tachometry i tachografy",
        "Tapicerka i pokrowce samochodowe",
        "Taxi",
        "Transport kolejowy",
        "Transport lotniczy",
        "Transport międzynarodowy",
        "Transport morski i śródlądowy",
        "Transport nadgabarytowy",
        "Transport samochodowy",
        "Transport ładunków niebezpiecznych",
        "Tuning samochodów",
        "Turbosprężarki",
        "Tłumiki i układy wydechowe",
        "Urządzenia parkingowe",
        "Usługi portowe i przeładunkowe",
        "Używane części samochodowe",
        "Wulkanizacja i serwis opon",
        "Wyciągi i koleje linowe",
        "Wynajem samochodów ciężarowych i dostawczych",
        "Wynajem samochodów i zarządzanie flotą",
        "Wynajem, serwis i sprzedaż autobusów",
        "Wyposażenie dodatkowe samochodów",
        "Wyposażenie warsztatów i myjni samochodowych",
        "Zabezpieczenia antykorozyjne samochodów",
        "Zabudowy nadwozi samochodowych",
        "Znakowanie i monitorowanie samochodów",
    ],
    "Nauka": [
        "Antykwariaty",
        "Artykuły biurowe",
        "Artykuły papiernicze",
        "Artykuły szkolne",
        "Badania i usługi archeologiczne",
        "Biblioteki i czytelnie",
        "Geolodzy i geofizycy",
        "Hurtownie artykułów biurowych",
        "Hurtownie artykułów papierniczych",
        "Hurtownie książek",
        "Instrumenty optyczne",
        "Instytuty i ośrodki badawcze",
        "Internaty i akademiki",
        "Korepetycje",
        "Księgarnie",
        "Kursy i nauka jazdy",
        "Kursy i szkolenia",
        "Ośrodki szkolno-wychowawcze",
        "Producenci artykułów biurowych",
        "Produkcja artykułów papierniczych",
        "Prywatne szkoły podstawowe",
        "Prywatne szkoły pomaturalne i policealne",
        "Prywatne szkoły ponadgimnazjalne",
        "Prywatne uniwersytety i szkoły wyższe",
        "Przedszkola prywatne",
        "Przedszkola publiczne",
        "Publiczne szkoły podstawowe",
        "Publiczne szkoły pomaturalne i policealne",
        "Publiczne uniwersytety i szkoły wyższe",
        "Sprzęt i wyposażenie laboratoriów",
        "Szkolenia zawodowe",
        "Szkoły artystyczne",
        "Szkoły i kursy językowe",
        "Szkoły ponadpodstawowe",
        "Szkoły tańca",
        "Taśmy samoprzylepne",
        "Żłobki publiczne",
    ],
    "Odzież i tekstylia": [
        "Akcesoria do butów",
        "Akcesoria szewskie i kaletnicze",
        "Artykuły dziecięce",
        "Bielizna",
        "Czapki i kapelusze",
        "Flagi i artykuły propagandowe",
        "Futra i kożuchy",
        "Galanteria",
        "Hafciarstwo",
        "Hurtownie bielizny",
        "Hurtownie obuwia",
        "Hurtownie odzieży",
        "Hurtownie tkanin i dzianin",
        "Kaletnictwo i rymarstwo",
        "Koszule i krawaty",
        "Krawiectwo",
        "Maszyny dziewiarskie",
        "Maszyny hafciarskie",
        "Obrusy",
        "Odzież damska",
        "Odzież dziecięca",
        "Odzież męska",
        "Odzież robocza",
        "Odzież skórzana",
        "Odzież sportowa",
        "Odzież używana",
        "Parasole",
        "Pasmanteria i dodatki krawieckie",
        "Pralnie i farbiarnie",
        "Produkcja bielizny",
        "Produkcja obuwia",
        "Produkcja odzieży",
        "Produkcja tkanin i dzianin",
        "Puch i pierze",
        "Rajstopy, pończochy i skarpety",
        "Ręczniki, koce i pościel",
        "Sklepy obuwnicze",
        "Sklepy odzieżowe",
        "Skóry naturalne i sztuczne",
        "Styliści, wizażyści i projektanci mody",
        "Suknie ślubne i komunijne",
        "Szewc",
        "Tkaniny i dzianiny",
        "Urządzenia do produkcji obuwia",
        "Wełna i przędza",
        "Wyposażenie pralni i farbiarni",
        "Wypożyczalnie strojów",
    ],
    "Porady": [
        "Pomysł na biznes",
    ],
    "Przemysł i energetyka": [
        "Aerozole",
        "Agregaty prądotwórcze",
        "Agregaty, komory i meble chłodnicze",
        "Akumulatory i baterie",
        "Armatura hydrauliczna",
        "Armatura przemysłowa",
        "Artykuły elektrotechniczne",
        "Artykuły metalowe",
        "Automatyka",
        "Autozłom",
        "Badania nieniszczące",
        "Biopaliwa",
        "Broń i amunicja",
        "Brykiety i węgiel drzewny",
        "Budowa i sprzęt drogowy",
        "Budowa i wyposażenie stacji paliw",
        "Budowa, wyposażenie i remont statków",
        "Budownictwo kolejowe",
        "Budownictwo przemysłowe",
        "Chemia gospodarcza",
        "Czyszczące urządzenia przemysłowe",
        "Czyściwa przemysłowe",
        "Drabiny",
        "Drewno",
        "Drewno budowlane",
        "Drewno opałowe",
        "Drut i liny stalowe",
        "Dystrybucja energii elektrycznej",
        "Dźwigi i żurawie",
        "Elektrociepłownie",
        "Elektronarzędzia",
        "Energia odnawialna",
        "Farby i lakiery",
        "Filtry",
        "Formy wtryskowe",
        "Galwanizacja",
        "Gaz ziemny",
        "Gazy techniczne",
        "Grzejnictwo elektryczne",
        "Górnicze materiały wybuchowe",
        "Hurtownie artykułów elektrotechnicznych",
        "Hurtownie artykułów metalowych",
        "Hurtownie chemii gospodarczej",
        "Hurtownie części elektronicznych",
        "Hurtownie farb, lakierów i emalii",
        "Hurtownie urządzeń elektrycznych",
        "Hurtownie środków chemicznych",
        "Hydraulika siłowa",
        "Hydrotechnika",
        "Instalacja i serwis ogrzewania",
        "Instalacje i urządzenia energetyczne",
        "Instalacje przemysłowe",
        "Inwestycje budowlane",
        "Kleje i żywice",
        "Kompresory",
        "Konstrukcje aluminiowe",
        "Konstrukcje stalowe",
        "Kontenery",
        "Kraty pomostowe",
        "Laminaty",
        "Lasery",
        "Liczniki energii elektrycznej",
        "Magnesy i elektromagnesy",
        "Malowanie i lakierowanie przemysłowe",
        "Maszty i słupy",
        "Maszyny do obróbki drewna",
        "Maszyny do obróbki metali",
        "Maszyny dziewiarskie",
        "Maszyny i sprzęt górniczy",
        "Maszyny pakujące",
        "Materiały do spawania i zgrzewania",
        "Materiały drewnopochodne",
        "Materiały elektryczne",
        "Materiały ognioodporne",
        "Materiały ścierne i polerskie",
        "Metale nieżelazne i kolorowe",
        "Metale żelazne",
        "Metalizowanie i powlekanie tworzyw",
        "Napełnianie butli gazowych",
        "Narzędzia",
        "Narzędzia pneumatyczne",
        "Obróbka metali",
        "Obróbka tworzyw sztucznych",
        "Odlewnie",
        "Ogrzewanie elektryczne",
        "Okucia",
        "Olej opałowy",
        "Oleje techniczne i smary",
        "Opakowania",
        "Opakowania foliowe",
        "Opakowania jednorazowe",
        "Opakowania z tworzyw sztucznych",
        "Palety",
        "Paliwa i opał ekologiczny",
        "Pasy napędowe i transportujące",
        "Piece",
        "Pirotechnika",
        "Pneumatyka siłowa",
        "Podnośniki",
        "Podzespoły elektroniczne",
        "Pompy",
        "Posadzki przemysłowe",
        "Prace podwodne",
        "Producenci farb i lakierów",
        "Produkcja artykułów elektrotechnicznych",
        "Produkcja artykułów higienicznych",
        "Produkcja artykułów metalowych",
        "Produkcja chemii gospodarczej",
        "Produkcja części elektronicznych",
        "Produkcja kosmetyków",
        "Produkcja sprężyn",
        "Produkcja urządzeń elektronicznych",
        "Produkcja urządzeń elektrycznych",
        "Produkcja zasłon, firanek i karniszy",
        "Produkcja środków chemicznych",
        "Przemysłowe urządzenia elektryczne",
        "Przenośniki",
        "Przewody, kable i światłowody",
        "Pędzle i szczotki",
        "Recykling",
        "Rury",
        "Sejfy i kasy pancerne",
        "Serwis urządzeń chłodniczych",
        "Serwis urządzeń elektrycznych",
        "Silikon",
        "Silniki i prądnice",
        "Sklepy z częściami elektronicznymi",
        "Sprzęt do produkcji opakowań",
        "Sprzęt do utylizacji odpadów",
        "Sprzęt i materiały hydrauliczne",
        "Sprzęt i zabezpieczenia przeciwpożarowe",
        "Sprzęt lotniczy",
        "Sprzęt radiokomunikacyjny",
        "Sprzęt torowy i kolejowy",
        "Stacje paliw",
        "Stal i wyroby stalowe",
        "Studnie",
        "Surowce mineralne",
        "Suwnice",
        "Systemy zamocowań",
        "Szkło budowlane",
        "Szkło przemysłowe",
        "Sznury, liny i nici",
        "Sól przemysłowa",
        "Tartaki",
        "Technika liniowa",
        "Techniki bezwykopowe",
        "Toalety przenośne",
        "Tworzywa sztuczne",
        "Urządzenia do produkcji obuwia",
        "Urządzenia elektroniczne",
        "Urządzenia elektryczne",
        "Urządzenia grzewcze",
        "Urządzenia i maszyny przemysłowe",
        "Urządzenia lakiernicze",
        "Urządzenia pneumatyczne",
        "Urządzenia pomiarowe",
        "Urządzenia spawalnicze i zgrzewające",
        "Uszczelki i uszczelnienia",
        "Usługi i projekty górnicze",
        "Usługi kamieniarskie",
        "Usługi spawania i zgrzewania",
        "Utylizacja odpadów",
        "Wagi",
        "Wodociągi i kanalizacja",
        "Wyciągi i koleje linowe",
        "Wydobycie i sprzedaż węgla",
        "Wynajem maszyn i narzędzi",
        "Wyposażenie, sprzęt i instalacje chłodnicze",
        "Wyroby hutnicze",
        "Wytwarzanie energii odnawialnej",
        "Wzornictwo przemysłowe",
        "Wózki widłowe",
        "Węże przemysłowe",
        "Zabezpieczenia antykorozyjne",
        "Zapalniczki i zapałki",
        "Zawiesia linowe, łańcuchowe i pasowe",
        "Zbiorniki i pojemniki",
        "Złom i surowce wtórne",
        "Łańcuchy",
        "Łożyska",
        "Świece i znicze",
    ],
    "Rolnictwo i leśnictwo": [
        "Artykuły rolnicze",
        "Giełdy",
        "Grzyby i runo leśne",
        "Hodowla i hurtownie ryb",
        "Hurtownie rolnicze",
        "Hurtownie roślin, nasion i cebulek",
        "Jaja",
        "Korek naturalny",
        "Leśnictwo",
        "Nawozy",
        "Ochrona środowiska",
        "Parki narodowe, krajobrazowe i rezerwaty",
        "Pasze",
        "Pieczarkarnie",
        "Produkcja artykułów rolniczych",
        "Produkcja roślin i nasion",
        "Rośliny, nasiona i cebulki",
        "Serwis sprzętu rolniczego",
        "Usługi rolnicze",
        "Wynajem magazynów",
        "Wynajem powierzchni chłodniczych",
        "Wyroby wiklinowe i bambusowe",
        "Zboża",
        "Zwierzęta hodowlane",
        "Środki ochrony roślin",
    ],
    "Rozrywka i rekreacja": [
        "Agencje artystyczne",
        "Akcesoria dla artystów i plastyków",
        "Antyki i dzieła sztuki",
        "Antykwariaty",
        "Artykuły zoologiczne",
        "Astrologia",
        "Automaty do gier",
        "Balony",
        "Bary",
        "Baseny i parki wodne",
        "Broń i amunicja",
        "Centra handlowe",
        "Cyrki i wesołe miasteczka",
        "Domy kultury i kluby osiedlowe",
        "Dyskoteki",
        "Escape rooms",
        "Filatelistyka",
        "Filatelistyka i numizmatyka",
        "Galerie sztuki",
        "Genealogia i heraldyka",
        "Gry komputerowe",
        "Hale widowiskowo-sportowe",
        "Hurtownie książek",
        "Hurtownie sprzętu sportowego i turystycznego",
        "Hurtownie zabawek",
        "Instrumenty i sklepy muzyczne",
        "Jachty",
        "Jeździectwo",
        "Kasyna i bukmacherzy",
        "Kawiarnie",
        "Kina",
        "Kluby muzyczne",
        "Kluby nocne",
        "Księgarnie",
        "Lecznice weterynaryjne",
        "Metaloplastyka",
        "Militaria",
        "Modelarstwo",
        "Muzea",
        "Myślistwo",
        "Nauka muzyki",
        "Nośniki danych i płyty CD i DVD",
        "Numizmatyka",
        "Odzież sportowa",
        "Ogrody zoologiczne i botaniczne",
        "Ośrodki i kluby sportowo-rekreacyjne",
        "Parki rozrywki",
        "Pirotechnika",
        "Pizzerie",
        "Pojazdy zabytkowe i dorożki",
        "Producenci sprzętu sportowego i turystycznego",
        "Produkcja zabawek",
        "Projektowanie i montaż placów zabaw",
        "Puby",
        "Ramy i oprawy obrazów",
        "Restauracje",
        "Rowery",
        "Rękodzieło artystyczne",
        "Sale weselne i organizacja wesel",
        "Sale zabaw",
        "Salony bilardowe",
        "Schroniska dla zwierząt",
        "Sex shopy",
        "Siłownie i fitness",
        "Sklepy z zabawkami",
        "Sprzęt i wyposażenie kręgielni",
        "Sprzęt i wyposażenie weterynaryjne",
        "Sprzęt sportowy i turystyczny",
        "Stadiony sportowe",
        "Systemy dźwiękowe i audio",
        "Szkoły tańca",
        "Teatry i filharmonie",
        "Wynajem i serwis sprzętu sportowego i turystycznego",
        "Wyposażenie obiektów sportowych",
        "Wypożyczalnie filmów wideo i DVD",
        "Wędkarstwo",
        "Zespoły muzyczne",
        "Zwierzęta domowe",
        "Świetlice środowiskowe",
        "Żegluga",
    ],
    "Telekomunikacja, Internet, technologie": [
        "Anteny",
        "Audyty oprogramowania i sprzętu komputerowego",
        "Informatyka",
        "Internet",
        "Odzyskiwanie i ochrona danych komputerowych",
        "Operatorzy telekomunikacyjni",
        "Oprogramowanie komputerowe",
        "Serwis komputerów",
        "Serwisy informacyjne",
        "Sieci komputerowe i integracja systemów",
        "Sprzęt i centrale telefoniczne",
        "Sprzęt radiokomunikacyjny",
        "Stacje radiowe i telewizyjne",
        "Systemy i technologie multimedialne",
        "Systemy i usługi telekomunikacyjne",
    ],
    "Turystyka": [
        "Agroturystyka",
        "Biura podróży i agencje turystyczne",
        "Hotele",
        "Informacja turystyczna",
        "Kempingi",
        "Komunikacja i przewozy pasażerskie",
        "Linie lotnicze",
        "Lotniska",
        "Namioty i hale namiotowe",
        "Noclegi i kwatery prywatne",
        "Noclegownie",
        "Pensjonaty, hostele i ośrodki wypoczynkowe",
        "Sprzedaż i rezerwacja biletów",
        "Wyposażenie hoteli",
    ],
    "Usługi dla firm": [
        "Adwokaci",
        "Agenci okrętowi i morscy",
        "Agencje fotograficzne",
        "Agencje i doradztwo reklamowe",
        "Agencje i składy celne",
        "Agencje marketingowe",
        "Agencje modelek",
        "Agencje ochrony",
        "Agencje pośrednictwa pracy",
        "Agencje pracy tymczasowej",
        "Agencje prasowe",
        "Agencje public relations",
        "Agencje tłumaczy",
        "Akcesoria i gadżety reklamowe",
        "Akcesoria szewskie i kaletnicze",
        "Archiwa i archiwizacja danych",
        "Artykuły i sprzęt BHP",
        "Artykuły i wyposażenie salonów fryzjerskich",
        "Automaty do sprzedaży",
        "Badania i monitoring rynku",
        "Badania i usługi archeologiczne",
        "Badania i uzdatnianie wody",
        "Banki",
        "Bazy danych",
        "Biura ogłoszeń",
        "Biura rachunkowe",
        "Biura reklamy",
        "Bony i kupony",
        "Budowa i wynajem hal przemysłowych",
        "Catering",
        "Czyszczenie strumieniowo-ścierne",
        "Czytniki i karty identyfikacyjne",
        "Dezynfekcja dezynsekcja i deratyzacja",
        "Doradztwo finansowe i kredytowe",
        "Doradztwo gospodarcze",
        "Doradztwo personalne",
        "Doradztwo podatkowe",
        "Doradztwo prawne",
        "Druk cyfrowy",
        "Druk na odzieży",
        "Druk offsetowy",
        "Druk plakatów wielkoformatowych",
        "Drukarnie i poligrafia",
        "Druki akcydensowe",
        "Elektroinstalatorstwo",
        "Etykiety i naklejki",
        "Firmy konsultingowe",
        "Flagi i artykuły propagandowe",
        "Geodezja",
        "Grafika komputerowa",
        "Grawerowanie",
        "Hale targów i wystaw",
        "Hurt i produkcja zegarów i zegarków",
        "Hurtownie sprzętu fotograficznego",
        "Import i eksport",
        "Informatyka",
        "Inkubatory przedsiębiorczości",
        "Instalacja systemów alarmowych",
        "Instytuty i ośrodki badawcze",
        "Internet",
        "Introligatornie",
        "Kadry i płace",
        "Kalendarze, katalogi i foldery reklamowe",
        "Karty kredytowe, płatnicze i programy lojalnościowe",
        "Kasy fiskalne i sklepowe",
        "Kolportaż gazet i czasopism",
        "Konserwacja zabytków",
        "Kredyty i finansowanie",
        "Ksero",
        "Kurierzy",
        "Kursy i szkolenia",
        "Leasing",
        "Lombardy",
        "Mapy i plany",
        "Maszyny do szycia",
        "Maszyny i materiały drukarskie",
        "Nawigacja i lokalizacja satelitarna",
        "Naświetlanie i skanowanie druku",
        "Nieruchomości",
        "Nietypowe usługi reklamowe",
        "Niszczenie dokumentów",
        "Obiekty konferencyjne",
        "Obsługa cudzoziemców",
        "Oczyszczanie ścieków",
        "Odszkodowania",
        "Odzież robocza",
        "Odzyskiwanie i ochrona danych komputerowych",
        "Oklejanie samochodów",
        "Opakowania papierowe i tekturowe",
        "Operatorzy logistyczni",
        "Operatorzy pocztowi",
        "Operatorzy telekomunikacyjni",
        "Organizacja i sprzęt dla targów i wystaw",
        "Organizacja imprez i konferencji",
        "Ostrzenie",
        "Osuszanie budynków",
        "Papier",
        "Plakatowanie",
        "Pomiary, konsultacje i badania BHP",
        "Pośrednictwo handlu",
        "Pośrednicy ubezpieczeniowi",
        "Prace podwodne",
        "Prace wysokościowe",
        "Pralnie i usługi czyszczenia",
        "Produkcja i dystrybucja filmów",
        "Przedstawicielstwa firm zagranicznych",
        "Radcy prawni",
        "Recykling",
        "Redakcje i wydawcy gazet i czasopism",
        "Reklama zewnętrzna",
        "Rewidenci i usługi audytorskie",
        "Rzecznicy patentowi",
        "Rzeczoznawcy",
        "Serwis i instalacja klimatyzacji",
        "Serwis kserokopiarek",
        "Sitodruk",
        "Skład tekstu do druku",
        "Specjalne strefy ekonomiczne",
        "Spedycja",
        "Spedycja międzynarodowa",
        "Sprzedaż wysyłkowa",
        "Sprzątanie terenu",
        "Sprzątanie wnętrz i mycie okien",
        "Sprzęt i centrale telefoniczne",
        "Sprzęt i wyposażenie kręgielni",
        "Stacje radiowe i telewizyjne",
        "Studia nagrań",
        "Syndycy i likwidatorzy",
        "Systemy audiowizualne",
        "Systemy i usługi telekomunikacyjne",
        "Systemy kontroli dostępu i czasu pracy",
        "Szyldy i banery",
        "Telebimy diodowe LED",
        "Telefony komórkowe",
        "Telemarketing",
        "Telewizja przemysłowa",
        "Telewizja satelitarna",
        "Torby, walizki i teczki",
        "Transport kolejowy",
        "Transport lotniczy",
        "Transport międzynarodowy",
        "Transport morski i śródlądowy",
        "Transport samochodowy",
        "Transport ładunków niebezpiecznych",
        "Tłumacze",
        "Tłumacze przysięgli",
        "Ubezpieczenia",
        "Usuwanie i neutralizacja azbestu",
        "Usługi dystrybucyjne",
        "Usługi gazownicze",
        "Usługi pakowania",
        "Usługi portowe i przeładunkowe",
        "Usługi sekretarskie",
        "Usługi wysyłkowe",
        "Utylizacja odpadów",
        "Ważne telefony",
        "Windykacja długów i należności",
        "Wirtualne biura",
        "Wycena nieruchomości",
        "Wydawnictwa",
        "Wynajem i sprzedaż kserokopiarek",
        "Wynajem magazynów",
        "Wynajem powierzchni chłodniczych",
        "Wyposażenie biur projektowych",
        "Wyposażenie hoteli",
        "Wyposażenie i narzędzia jubilerskie",
        "Wyposażenie i sprzęt dla kin i teatrów",
        "Wyposażenie i sprzęt introligatorski",
        "Wyposażenie i zaopatrzenie piekarni",
        "Wyposażenie klubów bilardowych",
        "Wyposażenie kwiaciarni",
        "Wyposażenie magazynów",
        "Wyposażenie pralni i farbiarni",
        "Wyposażenie salonów kosmetycznych",
        "Wyposażenie sklepów",
        "Wyposażenie stacji radiowo-telewizyjnych",
        "Wypożyczalnie strojów",
        "Wywiadownie gospodarcze",
        "Wywóz śmieci i odpadów",
        "Zaopatrzenie biur",
        "Zarządzanie nieruchomościami",
        "Znakowanie i monitorowanie samochodów",
        "Znakowanie, kodowanie i hologramy",
    ],
    "Usługi dla każdego": [
        "Adwokaci",
        "Agencje detektywistyczne",
        "Agencje fotograficzne",
        "Agencje ochrony",
        "Agencje pośrednictwa pracy",
        "Agencje pracy tymczasowej",
        "Agencje tłumaczy",
        "Astrologia",
        "Badania i uzdatnianie wody",
        "Bankomaty",
        "Baseny i parki wodne",
        "Bazy danych",
        "Biura matrymonialne",
        "Bony i kupony",
        "Budowa i wyposażenie saun",
        "Centra handlowe",
        "Czyszczenie i renowacja dywanów i wykładzin",
        "Czyszczenie strumieniowo-ścierne",
        "Deweloperzy",
        "Dewocjonalia",
        "Dezynfekcja dezynsekcja i deratyzacja",
        "Doradztwo podatkowe",
        "Doradztwo prawne",
        "Elektroakustyka",
        "Elektroinstalatorstwo",
        "Fryzjerzy i salony fryzjerskie",
        "Fundusze emerytalne",
        "Genealogia i heraldyka",
        "Grafika komputerowa",
        "Grawerowanie",
        "Handel obwoźny",
        "Handel złotem i srebrem",
        "Hotele dla zwierząt",
        "Hurt i produkcja zegarów i zegarków",
        "Hurtownie sprzętu fotograficznego",
        "Hydraulicy",
        "Internet",
        "Kaletnictwo i rymarstwo",
        "Kantory",
        "Kawiarenki internetowe",
        "Kominiarze",
        "Komisy",
        "Korepetycje",
        "Krawiectwo",
        "Ksero",
        "Kurierzy",
        "Kursy i nauka jazdy",
        "Kwiaciarnie",
        "Leczenie uzależnień",
        "Lombardy",
        "Lornetki i lunety",
        "Magiel",
        "Malowanie i tapetowanie",
        "Mapy i plany",
        "Maszyny do szycia",
        "Nieruchomości",
        "Notariusze",
        "Obsługa cudzoziemców",
        "Oczyszczanie ścieków",
        "Odszkodowania",
        "Odzyskiwanie i ochrona danych komputerowych",
        "Operatorzy pocztowi",
        "Operatorzy telekomunikacyjni",
        "Organizacja imprez i konferencji",
        "Ostrzenie",
        "Osuszanie budynków",
        "Pamiątki i upominki",
        "Papierosy elektroniczne",
        "Place i hale targowe",
        "Pocztówki i widokówki",
        "Pomoc domowa",
        "Pośrednicy ubezpieczeniowi",
        "Produkcja kosmetyków",
        "Przeprowadzki",
        "Radcy prawni",
        "Rzeczoznawcy",
        "Salony SPA i odnowa biologiczna",
        "Sejfy i kasy pancerne",
        "Serwis i instalacja klimatyzacji",
        "Sex shopy",
        "Siłownie i fitness",
        "Sklepy wielobranżowe",
        "Solaria",
        "Sprzedaż wysyłkowa",
        "Sprzątanie wnętrz i mycie okien",
        "Sprzęt fotograficzny",
        "Styliści, wizażyści i projektanci mody",
        "Supermarkety i hipermarkety",
        "Systemy i usługi telekomunikacyjne",
        "Szewc",
        "Tatuaże",
        "Taxi",
        "Telefony alarmowe",
        "Telefony komórkowe",
        "Telefony zaufania",
        "Telewizja kablowa",
        "Telewizja przemysłowa",
        "Telewizja satelitarna",
        "Torby, walizki i teczki",
        "Tłumacze",
        "Tłumacze przysięgli",
        "Ubezpieczenia",
        "Układanie gresu i płytek ceramicznych",
        "Układanie wykładzin podłogowych",
        "Usługi fotograficzne",
        "Usługi gazownicze",
        "Usługi kamieniarskie",
        "Usługi pogrzebowe",
        "Usługi tapicerskie",
        "Ważne telefony",
        "Wideofilmowanie",
        "Wycena nieruchomości",
        "Wypożyczalnie filmów wideo i DVD",
        "Wypożyczalnie strojów",
        "Wywóz śmieci i odpadów",
        "Zamki i zabezpieczenia antywłamaniowe",
        "Zegarmistrzowie",
        "Ślusarstwo i dorabianie kluczy",
        "Ślusarze",
    ],
    "Zdrowie i uroda": [
        "Alergolodzy",
        "Androlodzy",
        "Anestezjolodzy",
        "Aparaty słuchowe",
        "Apteki",
        "Artykuły i sprzęt pszczelarski",
        "Artykuły ortopedyczne",
        "Baseny i parki wodne",
        "Biżuteria sztuczna",
        "Biżuteria złota i srebrna",
        "Budowa i wyposażenie saun",
        "Chirurdzy",
        "Chirurgia plastyczna",
        "Dermatolodzy",
        "Diabetolodzy",
        "Dietetycy",
        "Domy i ośrodki pomocy społecznej",
        "Dozowniki mydła",
        "Endokrynolodzy",
        "Fryzjerzy dla zwierząt",
        "Fryzjerzy i salony fryzjerskie",
        "Gabinety podologiczne",
        "Gastrolodzy",
        "Genetycy",
        "Geriatrzy",
        "Ginekolodzy i położnicy",
        "Hematolodzy",
        "Homeopaci",
        "Hospicja",
        "Hurtownie artykułów higienicznych",
        "Hurtownie biżuterii",
        "Hurtownie farmaceutyczne",
        "Hurtownie kosmetyczne",
        "Instrumenty optyczne",
        "Interniści",
        "Jubilerstwo",
        "Kardiolodzy",
        "Laboratoria medyczne",
        "Laryngolodzy",
        "Leczenie chorób zakaźnych",
        "Leczenie uzależnień",
        "Lekarskie wizyty domowe",
        "Lekarze analitycy",
        "Lekarze medycyny estetycznej",
        "Lekarze medycyny paliatywnej",
        "Lekarze medycyny pracy",
        "Lekarze rodzinni",
        "Lekarze uzależnień alkoholowych",
        "Logopedzi",
        "Masaż",
        "Medycyna naturalna",
        "Mobilne usługi fryzjerskie",
        "Mobilne usługi kosmetyczne",
        "Narodowy Fundusz Zdrowia",
        "Nefrolodzy",
        "Neurochirurdzy",
        "Neurolodzy",
        "Odchudzanie",
        "Odżywki i suplementy diety",
        "Okulary",
        "Okuliści",
        "Onkolodzy",
        "Opieka prywatna nad osobami starszymi",
        "Optycy",
        "Ortodonci",
        "Ortopedzi",
        "Patomorfolodzy",
        "Pediatrzy",
        "Peruki i treski",
        "Pielęgniarki",
        "Pogotowie ratunkowe",
        "Praktyka lekarska",
        "Prezerwatywy",
        "Producenci farmaceutyków",
        "Produkcja artykułów higienicznych",
        "Produkcja kosmetyków",
        "Proktolodzy",
        "Przedłużanie i zagęszczanie włosów",
        "Przewozy osób niepełnosprawnych",
        "Przychodnie prywatne",
        "Psychiatrzy psycholodzy i psychoterapeuci",
        "Publiczne przychodnie i ośrodki zdrowia",
        "Pulmonolodzy",
        "Radiolodzy",
        "Rehabilitacja",
        "Rehabilitacja medyczna",
        "Reumatolodzy",
        "Salony SPA i odnowa biologiczna",
        "Salony i gabinety kosmetyczne",
        "Sanatoria",
        "Seksuolodzy",
        "Siłownie i fitness",
        "Sklepy z artykułami kosmetycznymi",
        "Solaria",
        "Sprzęt i materiały stomatologiczne",
        "Sprzęt i wyposażenie salonów SPA",
        "Sprzęt i wyposażenie solariów",
        "Sprzęt rehabilitacyjny",
        "Stomatolodzy i protetycy",
        "Styliści, wizażyści i projektanci mody",
        "Szkoły rodzenia",
        "Szpitale i kliniki prywatne",
        "Szpitale i kliniki publiczne",
        "Tatuaże",
        "Ubezpieczenia społeczne",
        "Urolodzy",
        "Wyposażenie i sprzęt medyczny",
        "Zakłady opiekuńczo-lecznicze",
        "Żywność ekologiczna",
    ],
    "Żywność i używki": [
        "Aromaty i dodatki do żywności",
        "Bary",
        "Catering",
        "Cukiernie i sklepy cukiernicze",
        "Cukrownie",
        "Grzyby i runo leśne",
        "Herbata",
        "Hodowla i hurtownie ryb",
        "Hurtownie alkoholi",
        "Hurtownie cukiernicze",
        "Hurtownie mięsa, wędlin i drobiu",
        "Hurtownie nabiału",
        "Hurtownie spożywcze",
        "Hurtownie warzyw i owoców",
        "Jaja",
        "Kawa",
        "Kawiarnie",
        "Miód i produkty pszczelarskie",
        "Mięso i wędliny",
        "Mrożonki",
        "Mąka",
        "Napoje orzeźwiające i wody",
        "Oleje i tłuszcze spożywcze",
        "Papierosy elektroniczne",
        "Papierosy i tytoń",
        "Piekarnie",
        "Pizzerie",
        "Producenci alkoholi",
        "Producenci i hurtownie lodów",
        "Producenci i hurtownie piwa",
        "Producenci i hurtownie żywności ekologicznej",
        "Producenci mięsa, wędlin i drobiu",
        "Producenci żywności",
        "Produkcja nabiału",
        "Produkcja wyrobów cukierniczych",
        "Przetwórstwo rybne",
        "Przetwórstwo warzyw i owoców",
        "Puby",
        "Rybołówstwo",
        "Ryby i owoce morza",
        "Sklepy monopolowe",
        "Sklepy owocowo-warzywne",
        "Sklepy spożywcze",
        "Urządzenia do produkcji żywności",
        "Wyposażenie i zaopatrzenie piekarni",
        "Zaopatrzenie i wyposażenie gastronomiczne",
        "Zioła i przyprawy",
        "Żywność ekologiczna",
    ],
}
